 tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "surface-variant": "#d9e2fc",
              "surface-dim": "#d1daf4",
              "on-secondary": "#ffffff",
              "on-primary": "#ffffff",
              error: "#ba1a1a",
              "on-primary-fixed-variant": "#0036bb",
              "error-container": "#ffdad6",
              "surface-container": "#e9edff",
              "on-error-container": "#93000a",
              "inverse-primary": "#b8c4ff",
              "secondary-fixed": "#dce1ff",
              "inverse-on-surface": "#edf0ff",
              "on-tertiary": "#ffffff",
              "surface-tint": "#154ceb",
              "secondary-fixed-dim": "#b6c4ff",
              "primary-container": "#315efb",
              "on-tertiary-fixed": "#002113",
              "primary-fixed": "#dde1ff",
              "surface-container-highest": "#d9e2fc",
              "on-tertiary-fixed-variant": "#005235",
              "on-primary-container": "#f1f1ff",
              "secondary-container": "#7896fe",
              "inverse-surface": "#273044",
              "on-error": "#ffffff",
              "on-secondary-fixed": "#00164f",
              primary: "#0042df",
              "surface-container-lowest": "#ffffff",
              "outline-variant": "#c4c5d8",
              "on-secondary-fixed-variant": "#173ea3",
              "surface-bright": "#f9f9ff",
              outline: "#747687",
              "on-surface-variant": "#434656",
              "on-surface": "#121b2e",
              secondary: "#3657bc",
              "on-background": "#121b2e",
              "primary-fixed-dim": "#b8c4ff",
              "on-primary-fixed": "#001354",
              "tertiary-container": "#017e54",
              "on-tertiary-container": "#c5ffdc",
              "surface-container-low": "#f1f3ff",
              "surface-container-high": "#e1e8ff",
              background: "#f9f9ff",
              "tertiary-fixed": "#93f6c3",
              tertiary: "#006341",
              "tertiary-fixed-dim": "#77daa8",
              "on-secondary-container": "#002a84",
              surface: "#f9f9ff",
            },
            borderRadius: {
              DEFAULT: "0.25rem",
              lg: "0.5rem",
              xl: "0.75rem",
              full: "9999px",
            },
            spacing: {
              "space-lg": "1.25rem",
              "space-xs": "0.25rem",
              "gutter-sm": "1rem",
              "space-md": "0.75rem",
              margin: "2rem",
              gutter: "1.5rem",
              "gutter-lg": "2rem",
              "margin-mobile": "1rem",
              "space-sm": "0.5rem",
              "space-xl": "2rem",
            },
            fontFamily: {
              "label-sm": ["Geist"],
              "headline-lg-mobile": ["Geist"],
              "metric-lg": ["Geist"],
              "display-hero": ["Geist"],
              "headline-lg": ["Geist"],
              "headline-md": ["Geist"],
              "metric-sm": ["Geist"],
              subtitle: ["Geist"],
              "body-base": ["Geist"],
              "body-medium": ["Geist"],
              "label-xs": ["Geist"],
              "display-hero-mobile": ["Geist"],
              "code-inline": ["JetBrains Mono"],
            },
            fontSize: {
              "label-sm": [
                "12px",
                {
                  lineHeight: "16px",
                  letterSpacing: "0.01em",
                  fontWeight: "500",
                },
              ],
              "headline-lg-mobile": [
                "26px",
                {
                  lineHeight: "34px",
                  letterSpacing: "-0.015em",
                  fontWeight: "600",
                },
              ],
              "metric-lg": [
                "32px",
                {
                  lineHeight: "36px",
                  letterSpacing: "-0.02em",
                  fontWeight: "600",
                },
              ],
              "display-hero": [
                "56px",
                {
                  lineHeight: "64px",
                  letterSpacing: "-0.03em",
                  fontWeight: "700",
                },
              ],
              "headline-lg": [
                "32px",
                {
                  lineHeight: "40px",
                  letterSpacing: "-0.02em",
                  fontWeight: "600",
                },
              ],
              "headline-md": [
                "24px",
                {
                  lineHeight: "32px",
                  letterSpacing: "-0.015em",
                  fontWeight: "600",
                },
              ],
              "metric-sm": [
                "20px",
                {
                  lineHeight: "24px",
                  letterSpacing: "-0.01em",
                  fontWeight: "600",
                },
              ],
              subtitle: [
                "16px",
                {
                  lineHeight: "24px",
                  letterSpacing: "-0.005em",
                  fontWeight: "400",
                },
              ],
              "body-base": [
                "14px",
                { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" },
              ],
              "body-medium": [
                "14px",
                {
                  lineHeight: "20px",
                  letterSpacing: "-0.005em",
                  fontWeight: "500",
                },
              ],
              "label-xs": [
                "11px",
                {
                  lineHeight: "14px",
                  letterSpacing: "0.02em",
                  fontWeight: "600",
                },
              ],
              "display-hero-mobile": [
                "36px",
                {
                  lineHeight: "44px",
                  letterSpacing: "-0.025em",
                  fontWeight: "700",
                },
              ],
              "code-inline": [
                "12px",
                { lineHeight: "16px", fontWeight: "400" },
              ],
            },
          },
        },
      };